### ISSUE TITLE
Mail 1 et 2

### ISSUE THREAD

**Issue by magmars** [soul9/AlternC#2]
Test d'envoie de mail à postmaster@marsnetest.alternc.roxor.me + marsnetest@alternc.roxor.me,
as-tu reçu quelque chose ? 
Préparation du test pour le sous-domaine vers roundcube test ac le pass actuel pour voir si réception de mails ok.

**Comment by magmars** [comment]
Pas les bons accès pour vérifier état de réception et envoie de mails.

**Comment by soul9** [comment]
non il faut envoyer a vos adresses mail que vous créez pour vos sous domaines. vous pouvez créer autant d'adresses que vous voulez.

**Comment by soul9** [comment]
voila j'ai modifié les quotas vous pouvez ajouter des adresses

**Comment by magmars** [comment]
J'ai voulue en ajouter une mais pas la possibilité.
On peut que "'modifier" l'adresse email existante.
![capture d ecran de 2017-10-09 14-09-09](https://user-images.githubusercontent.com/32638776/31337615-67b71aa2-acfc-11e7-928c-4338201b60ed.png)

**Comment by soul9** [comment]
reload? shift+F5?
![screenshot-2017-10-9 alternc control panel](https://user-images.githubusercontent.com/175965/31338029-158aa472-acfe-11e7-8f9f-0cf6382edaff.png)

**Comment by magmars** [comment]
Nikel comcrea@marsnetest.alternc.roxor.me marche très bienG' !
Création d'un nouveau mail > ok
Test envoie mail > ok
Test réception mail > ok
Config du mail en pop/imap, 10Mo.

**Comment by soul9** [comment]
10Mo? lapin comprendre.

**Comment by magmars** [comment]
Je lui ai mis 10Mo d'espace parce que c'est que un test, si jamais vous voulez en tester des centaines ou plus au moins z'aurez la place.

**Comment by soul9** [comment]
ha. ok. on peut fermer alors?

**Comment by magmars** [comment]
oui très bien, merci beaucoup.

**Comment by soul9** [comment]
p ;)
